[package]
name = "sudoku"
version = "0.1.0"
authors = ["Matthew Kennedy <MatthewKennedy2021@u.northwestern.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
indicatif = "*"
rayon = "*"

[profile.release]
debug = 1